// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ZkAceVerifier
 * @notice On-chain Groth16 BN254 verifier for ZK-ACE authorization proofs.
 *
 * @dev This contract verifies zero-knowledge proofs generated by the ZK-ACE
 *      protocol, which authorizes agent transactions without revealing the
 *      DSE's Root Entropy Value (REV).
 *
 *      Architecture:
 *      ┌─────────────────────────────────────────────────┐
 *      │  User → Yallet Extension                        │
 *      │  WASM: zkace_prove_wasm(mnemonic, ...) → proof  │
 *      │  REV extracted & zeroized inside WASM sandbox    │
 *      ├─────────────────────────────────────────────────┤
 *      │  proof + publicInputs submitted to EVM           │
 *      ├─────────────────────────────────────────────────┤
 *      │  ZkAceVerifier.verifyProof(proof, publicInputs) │
 *      │  Uses BN254 precompiles (ecAdd, ecMul, ecPairing)│
 *      └─────────────────────────────────────────────────┘
 *
     *      Public Inputs (5 field elements):
     *        [0] id_com  — Identity commitment: Poseidon(REV, salt, domain)
     *        [1] tx_hash — Transaction hash being authorized
     *        [2] domain  — Chain/application domain tag
     *        [3] target  — Target binding: Poseidon(Poseidon(REV, algId, ctxDomain, index))
     *        [4] rp_com  — Replay prevention commitment (nonce or nullifier)
 *
     *      Constraints verified in the circuit (C1–C5):
     *        C1: id_com  = Poseidon(rev, salt, domain)
     *        C2: target  = Poseidon(Poseidon(rev, algId, ctxDomain, index))
     *        C3: auth    = Poseidon(rev, algId, ctxDomain, index, tx_hash, domain, nonce)
     *        C4: rp_com  = Poseidon(id_com, nonce)           [NonceRegistry mode]
     *            OR rp_com = Poseidon(auth, domain)          [NullifierSet mode]
     *        C5: ctxDomain == domain
 *
     *      Two deployment instances are needed — one per replay mode:
     *        - NonceRegistry:  rp_com = Poseidon(id_com, nonce)
     *        - NullifierSet:   rp_com = Poseidon(auth, domain)
     */
contract ZkAceVerifier {
    // =========================================================================
    //  Errors
    // =========================================================================

    error InvalidProof();
    error InvalidPublicInputsLength();
    error PublicInputOutOfRange();
    error PairingFailed();

    // =========================================================================
    //  Constants — BN254 curve parameters
    // =========================================================================

    /// @dev BN254 scalar field order (Fr)
    uint256 internal constant PRIME_Q =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev Number of public inputs for ZK-ACE circuit
    uint256 internal constant NUM_PUBLIC_INPUTS = 5;

    // =========================================================================
    //  Verifying Key (set at deployment)
    // =========================================================================

    /// @dev Verifying key components from arkworks trusted setup.
    ///      These are immutable after deployment.

    // VK.alpha1 (G1 point)
    uint256 internal immutable VK_ALPHA1_X;
    uint256 internal immutable VK_ALPHA1_Y;

    // VK.beta2 (G2 point — note: x and y are each 2 field elements)
    uint256 internal immutable VK_BETA2_X1;
    uint256 internal immutable VK_BETA2_X2;
    uint256 internal immutable VK_BETA2_Y1;
    uint256 internal immutable VK_BETA2_Y2;

    // VK.gamma2 (G2 point)
    uint256 internal immutable VK_GAMMA2_X1;
    uint256 internal immutable VK_GAMMA2_X2;
    uint256 internal immutable VK_GAMMA2_Y1;
    uint256 internal immutable VK_GAMMA2_Y2;

    // VK.delta2 (G2 point)
    uint256 internal immutable VK_DELTA2_X1;
    uint256 internal immutable VK_DELTA2_X2;
    uint256 internal immutable VK_DELTA2_Y1;
    uint256 internal immutable VK_DELTA2_Y2;

    // VK.IC (input commitment points — G1, length = NUM_PUBLIC_INPUTS + 1)
    // IC[0] is the base, IC[1..5] correspond to public inputs
    uint256 internal immutable VK_IC0_X;
    uint256 internal immutable VK_IC0_Y;
    uint256 internal immutable VK_IC1_X;
    uint256 internal immutable VK_IC1_Y;
    uint256 internal immutable VK_IC2_X;
    uint256 internal immutable VK_IC2_Y;
    uint256 internal immutable VK_IC3_X;
    uint256 internal immutable VK_IC3_Y;
    uint256 internal immutable VK_IC4_X;
    uint256 internal immutable VK_IC4_Y;
    uint256 internal immutable VK_IC5_X;
    uint256 internal immutable VK_IC5_Y;

    // =========================================================================
    //  Constructor
    // =========================================================================

    /**
     * @notice Deploy the verifier with a specific verifying key.
     * @dev The verifying key is generated by the trusted setup ceremony
     *      and is specific to one replay mode (nonce or nullifier).
     *
     * @param alpha1 G1 point [x, y]
     * @param beta2  G2 point [x1, x2, y1, y2]
     * @param gamma2 G2 point [x1, x2, y1, y2]
     * @param delta2 G2 point [x1, x2, y1, y2]
     * @param ic     Array of G1 points [x0,y0, x1,y1, ..., x5,y5] (6 points = 12 values)
     */
    constructor(
        uint256[2] memory alpha1,
        uint256[4] memory beta2,
        uint256[4] memory gamma2,
        uint256[4] memory delta2,
        uint256[12] memory ic
    ) {
        VK_ALPHA1_X = alpha1[0];
        VK_ALPHA1_Y = alpha1[1];

        VK_BETA2_X1 = beta2[0];
        VK_BETA2_X2 = beta2[1];
        VK_BETA2_Y1 = beta2[2];
        VK_BETA2_Y2 = beta2[3];

        VK_GAMMA2_X1 = gamma2[0];
        VK_GAMMA2_X2 = gamma2[1];
        VK_GAMMA2_Y1 = gamma2[2];
        VK_GAMMA2_Y2 = gamma2[3];

        VK_DELTA2_X1 = delta2[0];
        VK_DELTA2_X2 = delta2[1];
        VK_DELTA2_Y1 = delta2[2];
        VK_DELTA2_Y2 = delta2[3];

        VK_IC0_X = ic[0];
        VK_IC0_Y = ic[1];
        VK_IC1_X = ic[2];
        VK_IC1_Y = ic[3];
        VK_IC2_X = ic[4];
        VK_IC2_Y = ic[5];
        VK_IC3_X = ic[6];
        VK_IC3_Y = ic[7];
        VK_IC4_X = ic[8];
        VK_IC4_Y = ic[9];
        VK_IC5_X = ic[10];
        VK_IC5_Y = ic[11];
    }

    // =========================================================================
    //  Public API
    // =========================================================================

    /**
     * @notice Verify a ZK-ACE Groth16 proof.
     *
     * @param a     Proof element A (G1 point): [x, y]
     * @param b     Proof element B (G2 point): [x1, x2, y1, y2]
     * @param c     Proof element C (G1 point): [x, y]
     * @param input Public inputs: [id_com, tx_hash, domain, target, rp_com]
     *
     * @return valid True if the proof is valid.
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[4] calldata b,
        uint256[2] calldata c,
        uint256[5] calldata input
    ) external view returns (bool valid) {
        // Validate public inputs are in the scalar field
        for (uint256 i = 0; i < NUM_PUBLIC_INPUTS; i++) {
            if (input[i] >= PRIME_Q) revert PublicInputOutOfRange();
        }

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        (uint256 vkx_x, uint256 vkx_y) = _computeLinearCombination(input);

        // Verify the pairing equation:
        //   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        //
        // Equivalently (using negation to avoid inversion):
        //   e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        valid = _verifyPairing(a, b, c, vkx_x, vkx_y);
    }

    /**
     * @notice Convenience function: verify and revert if invalid.
     */
    function verifyProofOrRevert(
        uint256[2] calldata a,
        uint256[4] calldata b,
        uint256[2] calldata c,
        uint256[5] calldata input
    ) external view {
        // Validate public inputs are in the scalar field
        for (uint256 i = 0; i < NUM_PUBLIC_INPUTS; i++) {
            if (input[i] >= PRIME_Q) revert PublicInputOutOfRange();
        }

        (uint256 vkx_x, uint256 vkx_y) = _computeLinearCombination(input);

        if (!_verifyPairing(a, b, c, vkx_x, vkx_y)) {
            revert InvalidProof();
        }
    }

    // =========================================================================
    //  Internal: Linear Combination
    // =========================================================================

    /**
     * @dev Compute vk_x = IC[0] + sum(input[i] * IC[i+1]) using ecMul and ecAdd.
     */
    function _computeLinearCombination(
        uint256[5] calldata input
    ) internal view returns (uint256, uint256) {
        // Start with IC[0]
        uint256 vkx_x = VK_IC0_X;
        uint256 vkx_y = VK_IC0_Y;

        // Accumulate: vkx += input[0] * IC[1]
        (uint256 mx, uint256 my) = _ecMul(VK_IC1_X, VK_IC1_Y, input[0]);
        (vkx_x, vkx_y) = _ecAdd(vkx_x, vkx_y, mx, my);

        // Accumulate: vkx += input[1] * IC[2]
        (mx, my) = _ecMul(VK_IC2_X, VK_IC2_Y, input[1]);
        (vkx_x, vkx_y) = _ecAdd(vkx_x, vkx_y, mx, my);

        // Accumulate: vkx += input[2] * IC[3]
        (mx, my) = _ecMul(VK_IC3_X, VK_IC3_Y, input[2]);
        (vkx_x, vkx_y) = _ecAdd(vkx_x, vkx_y, mx, my);

        // Accumulate: vkx += input[3] * IC[4]
        (mx, my) = _ecMul(VK_IC4_X, VK_IC4_Y, input[3]);
        (vkx_x, vkx_y) = _ecAdd(vkx_x, vkx_y, mx, my);

        // Accumulate: vkx += input[4] * IC[5]
        (mx, my) = _ecMul(VK_IC5_X, VK_IC5_Y, input[4]);
        (vkx_x, vkx_y) = _ecAdd(vkx_x, vkx_y, mx, my);

        return (vkx_x, vkx_y);
    }

    // =========================================================================
    //  Internal: Pairing Verification
    // =========================================================================

    /**
     * @dev Verify the Groth16 pairing equation using the bn256Pairing precompile.
     *
     *      We check: e(-A, B) · e(alpha, beta) · e(vk_x, gamma) · e(C, delta) == 1
     *
     *      Negating A (negating the y-coordinate in G1) converts the equation to:
     *        e(A, B) == e(alpha, beta) · e(vk_x, gamma) · e(C, delta)
     *
     *      The pairing precompile at 0x08 takes N pairs of (G1, G2) points and
     *      returns 1 if the product of pairings equals 1.
     */
    function _verifyPairing(
        uint256[2] calldata a,
        uint256[4] calldata b,
        uint256[2] calldata c,
        uint256 vkx_x,
        uint256 vkx_y
    ) internal view returns (bool) {
        // Negate A: -A = (a.x, -a.y mod p)
        // BN254 base field prime
        uint256 FIELD_P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        uint256 neg_ay = (FIELD_P - (a[1] % FIELD_P)) % FIELD_P;

        // Build input for ecPairing: 4 pairs × 6 uint256 = 24 uint256 = 768 bytes
        uint256[24] memory input;

        // Pair 1: e(-A, B)
        input[0]  = a[0];
        input[1]  = neg_ay;
        input[2]  = b[0];   // B.x (Fq2 imaginary part)
        input[3]  = b[1];   // B.x (Fq2 real part)
        input[4]  = b[2];   // B.y (Fq2 imaginary part)
        input[5]  = b[3];   // B.y (Fq2 real part)

        // Pair 2: e(alpha, beta)
        input[6]  = VK_ALPHA1_X;
        input[7]  = VK_ALPHA1_Y;
        input[8]  = VK_BETA2_X1;
        input[9]  = VK_BETA2_X2;
        input[10] = VK_BETA2_Y1;
        input[11] = VK_BETA2_Y2;

        // Pair 3: e(vk_x, gamma)
        input[12] = vkx_x;
        input[13] = vkx_y;
        input[14] = VK_GAMMA2_X1;
        input[15] = VK_GAMMA2_X2;
        input[16] = VK_GAMMA2_Y1;
        input[17] = VK_GAMMA2_Y2;

        // Pair 4: e(C, delta)
        input[18] = c[0];
        input[19] = c[1];
        input[20] = VK_DELTA2_X1;
        input[21] = VK_DELTA2_X2;
        input[22] = VK_DELTA2_Y1;
        input[23] = VK_DELTA2_Y2;

        // Call bn256Pairing precompile (address 0x08)
        uint256[1] memory result;
        bool success;
        assembly {
            success := staticcall(
                gas(),
                0x08,           // ecPairing precompile address
                input,
                768,            // 24 * 32 bytes
                result,
                32              // output: 1 uint256
            )
        }

        if (!success) revert PairingFailed();

        return result[0] == 1;
    }

    // =========================================================================
    //  Internal: EC Precompiles
    // =========================================================================

    /**
     * @dev Scalar multiplication on BN254 G1.
     *      Calls precompile at address 0x07.
     */
    function _ecMul(
        uint256 px,
        uint256 py,
        uint256 scalar
    ) internal view returns (uint256, uint256) {
        uint256[3] memory input;
        input[0] = px;
        input[1] = py;
        input[2] = scalar;

        uint256[2] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }
        require(success, "ecMul failed");

        return (result[0], result[1]);
    }

    /**
     * @dev Point addition on BN254 G1.
     *      Calls precompile at address 0x06.
     */
    function _ecAdd(
        uint256 p1x,
        uint256 p1y,
        uint256 p2x,
        uint256 p2y
    ) internal view returns (uint256, uint256) {
        uint256[4] memory input;
        input[0] = p1x;
        input[1] = p1y;
        input[2] = p2x;
        input[3] = p2y;

        uint256[2] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }
        require(success, "ecAdd failed");

        return (result[0], result[1]);
    }
}
